gestion_actividades/actividades/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'actividades.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.urls')),
)

gestion_actividades/apps/empleados/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'asignar_tareas/', include('apps.empleados.tareas.urls')),
)

gestion_actividades/apps/registro/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'actividad/', include('apps.registro.actividad.urls')),
                       url(r'administrador/', include('apps.registro.administrador.urls')),
)

gestion_actividades/apps/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'^', include('apps.login.urls')),
                       url(r'^menu/', include('apps.menu.urls')),
                       )

gestion_actividades/apps/empleados/tareas/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.configuraciones.models import Departamento
from apps.registro.administrador.models import Actividad
from apps.usuario_depart.models import UsuarioDepart

PORCENTAJE = (
    ('0', "Seleccione"),
    ('1', '10%'),
    ('2', '20%'),
    ('3', '30%'),
    ('4', '40%'),
    ('5', '50%'),
    ('6', '60%'),
    ('7', '70%'),
    ('8', '80%'),
    ('9', '90%'),
    ('10', '100%'),
)


class Empleados(models.Model):
    
    codigoE = models.CharField(max_length=50)
    cod_actividad_e = models.ForeignKey(Actividad, null=True, blank=True)
    codigoDepartamento_e = models.ForeignKey(Departamento, related_name='empleado_departamento', null=True, blank=True)
    empleados = models.ForeignKey(User, related_name='*', null=True, blank=True)
    nom_actividad_e = models.TextField(max_length=300, null=True, blank=True)
    des_actividad_e = models.TextField(max_length=300, null=True, blank=True)
    fecha_i_e = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    fecha_p_e = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    fechaP_a_e = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    indicaciones_e = models.TextField(max_length=300, null=True, blank=True)
    porcentaje = models.CharField(choices=PORCENTAJE, default=0, max_length=3, null=True, blank=True)
   
    
    #  Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    
    class Meta:
        """ Ordena los registros en base a el campo fechaI_a."""
        ordering = ('codigoE',)  # Ordenado por

    def __unicode__(self):
        return self.codigoE

gestion_actividades/apps/registro/actividad/models.py
from django.db import models
from apps.registro.administrador.models import Actividad
from apps.configuraciones.models import Departamento
from django.contrib.auth.models import User

ESTATUS = (
    ('0', "Seleccione"),
    ('1', 'Activo'),
    ('2', 'Inactivo'),
)

PORCENTAJE = (
    ('0', "Seleccione"),
    ('1', '10%'),
    ('2', '20%'),
    ('3', '30%'),
    ('4', '40%'),
    ('5', '50%'),
    ('6', '60%'),
    ('7', '70%'),
    ('8', '80%'),
    ('9', '90%'),
    ('10', '100%'),
)

class Registros(models.Model):
    
    cod_actividad = models.ForeignKey(Actividad)
    cod_departamento = models.ForeignKey(Departamento, null=True, blank=True)
    nom_actividad = models.CharField(max_length=100)
    des_actividad = models.TextField(max_length=300)
    porcentaje = models.CharField(choices=PORCENTAJE, default=0, max_length=3)
    status     = models.CharField(choices=ESTATUS, default=0, max_length=1)
    fecha_i    = models.DateField(auto_now_add=False, auto_now=False)
    fecha_p    = models.DateField(auto_now_add=False, auto_now=False)
    fecha_f    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    observacion = models.TextField(null=True, blank=True)
    fecha_o    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
        
    #  Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    
    class Meta:
        """ Ordena los registros en base a el campo cod_estado."""
        ordering = ('cod_actividad',)  # Ordenado por

    def __unicode__(self):
        return self.cod_actividad

gestion_actividades/apps/empleados/tareas/views.py
from django.views.generic import CreateView, ListView, UpdateView
from django.core.urlresolvers import reverse_lazy
from .models import Empleados
from apps.registro.administrador.models import Actividad
from apps.registro.actividad.models import Registros
from django.contrib.auth.models import User
from apps.usuario_depart.models import UsuarioDepart
from apps.configuraciones.models import Departamento
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db import connection
import time
import json
from django.db.models import Q
import re

class RegistrarEmpleados(CreateView):
    template_name = 'registros/empleados/empleados_tareas.html'
    model = Empleados
    success_url = reverse_lazy("listado_emp")
    
    def get_context_data(self, **kwargs):
        context = super(RegistrarEmpleados, self).get_context_data(**kwargs)
        
        usuario = self.request.user
        departamento_id = usuario.usuariodepart.departamento_id
        ##grupo_id = usuario.usuariodepart.grupo_usuario
        
        actividades = Registros.objects.all()
        actividades_f = actividades.filter(cod_departamento_id=departamento_id) 
        actividades_v =  actividades_f.values('cod_actividad__id','cod_actividad__cod_actividad')
        
        codigoE = Empleados.objects.order_by('-id').values('codigoE')[:1] # ordenar de forma decendente y traer solo 
        if codigoE.count() > 0:
            codigoE = re.findall(r'\d+', codigoE[0]['codigoE']) # extraer solo numeros 
            codigoE =  int(codigoE[0]) # convertir a entero osea eliminar los 0 a las izquierda
            codigoE = "E"+str(codigoE+1).zfill(4) # sumo 1 y  rellenar con 4 "0" a la izquierda
        else:
            codigoE = "E"+str(codigoE.count()+1).zfill(4) 

        empleados = UsuarioDepart.objects.all().filter(departamento_id=departamento_id, grupo_usuario=3)
        empleados_id = empleados.values('usuario_id')
      
        emple = User.objects.all().filter(id=empleados_id)
        
        context['codigoE'] = codigoE
        context['usuario_E'] = usuario
        context['lista_emp'] = emple
        context['actividad_e'] = actividades_v
        return context
    
    def post(self, request, *args, **kwargs):
        
        codigo = request.POST.get('codigoE')
        
        existe_codigo = Empleados.objects.filter(codigoE=codigo).exists()
        
        if existe_codigo:
            return HttpResponse('existe_cod')
        else:
            
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            
            if form.is_valid():
                
                
                add = form.save(commit=False)
                add.save()
                
                return HttpResponse('/menu/empleados/asignar_tareas/listado_emp/')
            
class ListarEmpleados(ListView):
    template_name = 'registros/empleados/lista_empleados.html'
    model = Empleados
    context_object_name = "lista_empleados"
    
class ActualizarEmpleados(UpdateView):
    template_name = 'registros/empleados/empleados_editar.html'
    model = Empleados
    success_url = reverse_lazy("listado_emp")
    context_object_name = "empleados_act" 
    
    def get_context_data(self, **kwargs):
        context = super(ActualizarEmpleados, self).get_context_data(**kwargs)
        
        usuario = self.request.user
        departamento_id = usuario.usuariodepart.departamento_id
        
        actividades = Registros.objects.all()
        actividades_f = actividades.filter(cod_departamento_id=departamento_id) 
        actividades_v =  actividades_f.values('cod_actividad__id','cod_actividad__cod_actividad')
        
        codigoE = Empleados.objects.order_by('-id').values('codigoE')[:1] # ordenar de forma decendente y traer solo 
        if codigoE.count() > 0:
            codigoE = re.findall(r'\d+', codigoE[0]['codigoE']) # extraer solo numeros 
            codigoE =  int(codigoE[0]) # convertir a entero osea eliminar los 0 a las izquierda
            codigoE = "E"+str(codigoE+1).zfill(4) # sumo 1 y  rellenar con 4 "0" a la izquierda
        else:
            codigoE = "E"+str(codigoE.count()+1).zfill(4) 

        empleados = UsuarioDepart.objects.all().filter(departamento_id=departamento_id, grupo_usuario=3)
        empleados_id = empleados.values('usuario_id')
      
        emple = User.objects.all().filter(id=empleados_id)

        context['codigoE'] = codigoE
        context['usuario_E'] = usuario
        context['lista_emp'] = emple
        context['actividad_e'] = actividades_v
        return context

def BuscarActivi_e(request):

    id_tareas_e = request.GET['id']
    
    actividad = Actividad.objects.filter(id=id_tareas_e)

    
    data = serializers.serialize('json', actividad,
                                 fields=('nom_actividad', 'des_actividad', 'fecha_i', 'fecha_p'))
   
    return HttpResponse(data, content_type='application/json')

def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

gestion_actividades/apps/registro/administrador/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Actividad
from apps.configuraciones.models import Departamento
from apps.registro.actividad.models import Registros
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.models import User
import time
import json
import re

class RegistrarAct(CreateView):
    template_name = 'registros/administrador/actividades.html'
    model = Actividad
    success_url = reverse_lazy("listando")
    
    def get_context_data(self, **kwargs):
        context = super(RegistrarAct, self).get_context_data(**kwargs)
        
        fecha_i = time.strftime("%d/%m/%Y")
        usuario_id = self.request.user.id
        usuario = User.objects.get(id=usuario_id).username
        
        codigo = Actividad.objects.order_by('-id').values('cod_actividad')[:1] # ordenar de forma decendente y traer solo 1
        
        if codigo.count() > 0:
            
            codigo = re.findall(r'\d+', codigo[0]['cod_actividad']) # extraer solo numeros 
            codigo =  int(codigo[0]) # convertir a entero osea eliminar los 0 a las izquierda
            codigo = "C"+str(codigo+1).zfill(4) # sumo 1 y  rellenar con 4 "0" a la izquierda
        else:
            codigo = 'C0001'
        departamento = Departamento.objects.all()
       
        context['fecha_i'] = fecha_i
        context['usuario'] = usuario
        context['codigo'] = codigo
        context['lista_departamento'] = departamento
        return context
    
    def post(self, request, *args, **kwargs):
       
        codigo = request.POST.get('cod_actividad')

        existe_codigo = Actividad.objects.filter(cod_actividad=codigo).exists()
        if existe_codigo == True:
            return HttpResponse('existe_codigo')
        else:
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            if form.is_valid():
                form.save()
                return HttpResponse('/menu/registros/administrador/listar/')
 
class ListarAct(ListView):
    
    template_name = 'registros/administrador/listado.html'
    model = Actividad
    
    def get_context_data(self, **kwargs):
        context = {}
        usuario_id = self.request.user.id
        es_administrador = self.request.user.groups.all().filter(name='administrador').exists()
        
        data = {}
        datos = []
            
        if es_administrador:
            actividades = Actividad.objects.all()
            actividades_f = actividades.filter(user_create_id=usuario_id)
            actividades_v = actividades.values('id', 'porcentaje', 'cod_actividad','departamento', 'departamento__siglas', 'departamento__nom_departamento', 'nom_actividad', 'status', 'fecha_p', 'fecha_f')
            for n in actividades_v:
                data = n
                datos.append(data)
           
        context['listado'] = datos
        return context

class Visualizar(UpdateView):
    template_name = 'registros/administrador/visualizar.html'
    model = Actividad
    context_object_name = "registro_act"
    success_url = reverse_lazy("listando")
    
    def get_context_data(self, **kwargs):
        context = super(Visualizar, self).get_context_data(**kwargs)
        
        fecha_i = time.strftime("%d/%m/%Y")
        fecha_p = time.strftime("%d/%m/%Y")
        usuario_id = self.request.user.id
        usuario = User.objects.get(id=usuario_id).username
        departamento = Departamento.objects.all()
       
        context['fecha_i'] = fecha_i
        context['fecha_p'] = fecha_p
        context['usuario'] = usuario
        context['lista_departamento'] = departamento
        return context

class ActualizarAct(UpdateView):
    template_name = 'registros/administrador/actualizar.html'
    model = Actividad
    success_url = reverse_lazy("listando")
    context_object_name = "registro_act" 
    
    def get_context_data(self, **kwargs):
        context = super(ActualizarAct, self).get_context_data(**kwargs)
        
        fecha_i = time.strftime("%d/%m/%Y")
        fecha_p = time.strftime("%d/%m/%Y")
        fecha_o = time.strftime("%d/%m/%y")
        usuario_id = self.request.user.id
        usuario = User.objects.get(id=usuario_id).username
        
        codigo = Actividad.objects.order_by('-id').values('cod_actividad')[:1] 
        codigo = re.findall(r'\d+', codigo[0]['cod_actividad'])
        codigo =  int(codigo[0])
        codigo = "C"+str(codigo+1).zfill(4)
        
        departamento = Departamento.objects.all()
        
        id_act = self.kwargs['pk']
        actividades = Registros.objects.all()
        actividades_f = actividades.filter(cod_actividad_id=id_act)
        
        context['registro_existe'] = 0
        
        if actividades_f.exists():
            context['registro_existe'] = 1
        
        
        context['fecha_i'] = fecha_i
        context['fecha_p'] = fecha_p
        context['fecha_o'] = fecha_o
        context['usuario'] = usuario
        context['codigo'] = codigo
        context['lista_departamento'] = departamento
        return context
    
    def post(self, request, *args, **kwargs):

        id_act = request.POST.get('cod_actividad')
        observacion = request.POST.get('observacion')
        fecha_o = request.POST.get('fecha_o')
        porcentaje = request.POST.get('porcentaje')
        
        id_adm = Actividad.objects.filter(cod_actividad=id_act).values('id')
        date = fecha_o.split("/")
        try:
            nueva_fecha = date[2]+"-"+date[1]+"-"+date[0]
        
        except:
            nueva_fecha = None
            
        if nueva_fecha != None:
            
            Registros.objects.filter(cod_actividad_id=id_adm).update(observacion=observacion, porcentaje=porcentaje, fecha_o=nueva_fecha)
            Actividad.objects.filter(id=id_adm).update(observacion=observacion, porcentaje=porcentaje, fecha_o=nueva_fecha)
            
        
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        add = form.save(commit=False)
        if form.is_valid():
            add.id = self.kwargs['pk']
            add.save()
        return HttpResponse('procesado')

class EliminarAct(DeleteView):
    template_name = 'registros/administrador/eliminar.html'
    model = Actividad
  
    def delete(self, request, *args, **kwargs):
        response_data = {}
        existe = Registros.objects.filter(cod_actividad_id=self.kwargs['pk'])
        if existe.exists():
            response_data['existe'] = 'si'
        else:
            existe = Actividad.objects.filter(id=self.kwargs['pk'])
            print existe
            if existe.exists():
                self.object = self.get_object()
                self.object.delete()
                response_data['eliminado'] = 'ok'
        
        return HttpResponse(json.dumps(response_data), status=200, content_type='application/json')

gestion_actividades/templates/registros/empleados/empleados_editar.html
{% extends "base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block contenido %}
<script type="text/javascript">
	$(document).ready(function(){
		
		$('#registrar_tareas').click(function(e){
			
			//Para validar campos vacios
			var empleados = $('#empleados').find('option').filter(':selected').val()
			//var departamento = $('#codigoDepartamento').find('option').filter(':selected').val()
			//var codigo = $('#id_cod_actividad').find('option').filter(':selected').val()
	
			if (empleados == 0) {
				bootbox.alert('Debe seleccionar el empleado para asignar la actividad', function() {
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#empleados').parent('div').addClass('has-error'); // colocar class has-error de boostrap
					$('#empleados').focus() 
				});
			}/*else if (codigo == 0){
				bootbox.alert('Debe seleccionar el codigo, según el departamento seleccionado', function() {
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#id_cod_actividad').parent('div').addClass('has-error'); // colocar class has-error de boostrap
					$('#id_cod_actividad').focus() 
				});
			}else if (departamentoA == 0){
				bootbox.alert('Debe seleccionar el departamento para asignar la actividad', function(){
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#codigoDepartamentoA').parent('div').addClass('has-error');
					$('#codigoDepartamentoA').focus() 
				});
			}
			else if ($('#indicaciones').val().trim() == ''){
				bootbox.alert('Debe indicar los requerimientos para esta actividad', function(){
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#indicaciones').parent('div').addClass('has-error');
					$('#indicaciones').focus() 
				});
			}*/
			else{
				$('#codigoE,#nom_actividad_e,#id_fecha_i_e,#id_fecha_p_e,#id_des_actividad_e,#id_cod_actividad_e').prop('disabled',false);
				$.post('',$('#form_empleados').serialize(),function(response){
					if (response == 'existe_cod') {
						bootbox.alert("Esta actividad ya esta registrada", function() {
							$('.nav-tabs a[href=#tabs_A]').tab('show') ;
							$('#codigoE').parent('div').addClass('has-error'); // colocar class has-error de boostrap
						});
					}else{
						url = '/menu/empleados/asignar_tareas/listado_emp'
						window.location = url
					}
				});
			}
	
		})
		
		$('#fechaP_a_e').datepicker({
			format: "dd/mm/yyyy",
			language: "es",
			startDate: "+1d",
			//daysOfWeekDisabled: "0,6",
			autoclose: true,
			
		})
		
		//.change(function () {
		//	var primera = Date.parse($("#id_fecha_p").val()); //fecha pautada
		//	var segunda = Date.parse($("#fechaP_a").val()); //fecha asignar
		//			 
		//		if (segunda > primera) {
		//			alert("Debe seleccionar una fecha menor");
		//			$("#fechaP_a").val($("#id_fecha_p").val())
		//		}
		//});
		
		//.on('changeDate', function(ev){
		//	var primera = Date.parse($("#id_fecha_p").val()); //fecha pautada
		//	var segunda = Date.parse($("#fechaP_a").val()); //fecha asignar
		//	//var value = $("#id_fecha_p input").datepicker("getDate");
		//	//
		//	//$("#fechaP_a").datepicker("setValue", "02-17-2012");
		//
		//		if (segunda > primera) {
		//			alert("Debe seleccionar una fecha menor");
		//			$("#fechaP_a").val('')
		//		}
		//});
		 
		///// Para validar campos numericos, alfanumericos y seleccion
		$("#id_cod_actividad_e,#empleados").select2();
		$('#nom_actividad_e,#indicaciones_e').alphanumeric({allow:"´,@,-.# "}); //Valida solo valores numericos y texto
		//$('#id_edad,#id_cedula,#id_telefono1,#id_telefono2').numeric(); //Valida solo permite valores numericos
			
		$('#volver').click(function(){
			url = '/menu/empleados/asignar_tareas/listado_emp'
			window.location = url
		})
		$('#limpiar').click(function(){
			$('#id_cod_actividad_e,#empleados').select2('val', '0');
		})
		
		$("#todos_e").click(function() {  
			if($(this).is(':checked')) {
				var data = $('#empleados').find('option')
				var valores = new Array();
				
				$.each(data, function() {
					
					valores.push($(this).val())
				});
				//console.log(valores)
				$('#empleados').val(valores).trigger("change"); 
			}  
		});
			
	});

</script>
<style>
    label{
        font-weight: bold
    }
</style>
    <html>
        <body>
            <form method="post" id="form_empleados" enctype="multipart/form-data">
                {% csrf_token %}
				<br/>
                <div style="width: 100%;text-transform:uppercase;box-shadow: 0 1px 5px rgba(0,0,0,.85); text-align: left" class="panel panel-danger">
					<div class="panel-heading">
						<label style="float: left" class="panel-title " ><a style="color: white" href="/menu/empleados/tareas/listado_emp" >Actividad</a>
						> Asignar</label>
						<br>
					</div>
                    <div class="panel-body">
                        <!-- Apertura de Tabs (Secciones) -->
                        <ul class="nav nav-tabs">
                            <li class="active" data-toggle="popover" data-trigger="focus" title="Datos de la actividad" data-content="En este panel se ingresan los datos requeridos para asignar una actividad" data-placement="top">
                                <a data-toggle="tab" href="#tabs_A">Tareas</a>
                            </li>
                        </ul>
                        <!-- Cierre de Tabs (Secciones) -->
                        <!-- Apertura de tabs (Contenidos) -->
                        <div class="tab-content">
                            <div id="tabs_A" class="tab-pane fade in active">
                                <div class="panel-body">
                                <!-- Apertura de datos para asignar actividad a otros departamentos  -->
								<div class="form-group col-xs-1"><label>Usuario</label></div>
                                <div class="form-group col-xs-2">
                                    <span style="color: red; font-weight: bold">{{usuario_E|upper}}</span>
                                </div>
								<div class="form-group col-xs-5">
									<input id="codigoAB" maxlength="30"  style="width: 100%;" name="codigoAB" type="hidden" value="" disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Código</label></div>
								<div class="form-group col-xs-3">
									<input id="codigoE" maxlength="30"  style="width: 100%;" name="codigoE" type="text" value="{{empleados_act.codigoE}}" disabled='disabled'/>
								</div>
								<br/><br/><br/>
                                <fieldset><legend style="text-align: left">Asignar Tareas a empleados</legend></fieldset>
                                <div class="form-group col-xs-1"><label>Gerencia</label></div>
                                <div class="form-group col-xs-11">
                                    <input id="cod_departamento" name="codigoDepartamento_e" type="hidden" value="{{user.usuariodepart.departamento.id}}"/>
									<input id="departamento" maxlength="30"  style="width: 100%;text-align: left" name="departamento" type="text" disabled='disabled' value="{{user.usuariodepart.departamento.nom_departamento}}"/>
                                </div>
								<div class="form-group col-xs-1"><label>Código</label></div>
								<div class="form-group col-xs-2">
									<select style="width:100%;text-align: center" class="form-control input-sm" id="id_cod_actividad_e" name="cod_actividad_e" disabled='disabled'>
										<option value="0">SELECCIONE</option>
										{% for act in actividad_e %}
											{% if act.pk == empleados_act.cod_actividad_id %}
												<option value='{{act.cod_actividad__id}}' selected='selected'>{{act.cod_actividad__cod_actividad}}</option>
											{% endif %}
											{% if not act.pk == empleados_act.cod_actividad_id %}
                                                <option value='{{act.cod_actividad__id}}'>{{act.cod_actividad__cod_actividad}}</option>
											{% endif %}
										{% endfor %}
									</select>
								</div>
								<div class="form-group col-xs-1"><label>Nombre</label></div>
								<div class="form-group col-xs-8">
									<input id="nom_actividad_e" maxlength="30"  style="width: 100%; text-align: center; text-transform:uppercase;" name="nom_actividad_e" type="text" value='{{empleados_act.nom_actividad_e}}' disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Descripción</label></div>
								<div class="form-group col-xs-12">
									<textarea cols="70" id="id_des_actividad_e" name="des_actividad_e" rows="05" style="width: 100%;text-align: justify; text-transform:uppercase;" disabled='disabled'>{{empleados_act.des_actividad_e}}</textarea>
								</div>
								<div class="form-group col-xs-1"><label>Inicial</label></div>
								<div class="form-group col-xs-3">
									<input id="id_fecha_i_e" maxlength="30"  style="width: 100%;text-align: center" name="fecha_i_e" type="text" value="{{empleados_act.fecha_i_e |date:"SHORT_DATE_FORMAT"}}" disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Pautada</label></div>
								<div class="form-group col-xs-3">
									<input id="id_fecha_p_e" maxlength="30"  style="width: 100%;text-align: center" name="fecha_p_e" type="text" value="{{empleados_act.fecha_p_e |date:"SHORT_DATE_FORMAT"}}" disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Asignada</label></div>
								<div class="form-group col-xs-3">
									<input id="fechaP_a_e" maxlength="30"  style="width: 100%;text-align: center" name="fechaP_a_e" type="text" value="{{empleados_act.fechaP_a_e |date:"SHORT_DATE_FORMAT"}}"/>
								</div>
								<div class="form-group col-xs-2"><label>Seleccionar Todos</label></div>
								<div class="form-group col-xs-10">
									<input type="checkbox" id="todos_e">
								</div>
								<div class="form-group col-xs-12">
									<label>Asignar a:</label>
									<select style="width:100%;text-align: left" class="form-control input-sm" id="empleados" name="empleados" data-placeholder="SELECCIONE" multiple='multiple'>
										{% for emp in lista_emp %}
											{% if emp.id == empleados_act.empleados_id %}
												<option value="{{emp.id}}" selected='selected'>{{emp.first_name}} {{emp.last_name}}</option>
											{% endif %}
											{% if not emp.id == empleados_act.empleados_id %}
												<option value="{{emp.id}}">{{emp.first_name}} {{emp.last_name}}</option>
											{% endif %}
										{% endfor %}
									</select>
								</div>
								<div class="form-group col-xs-12">
									<label>Indicaciones</label>
									<textarea cols="70" id="indicaciones_e" name="indicaciones_e" rows="05" style="width: 100%;text-align: justify; text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" >{{empleados_act.indicaciones_e}}</textarea>
								</div>
                            </div>
                       </div>
                    </div>
                </div>
                
				<input id='user_update' type="hidden" name='user_update' value='{{ user.id }}'>
				<input id='user_create' type="hidden" name='user_create' value='{{empleados_act.user_create.id}}'>
				<input id='porcentaje' type="hidden" name='porcentaje' value='0'>
                <div class="row" style="text-align: center">
                    <button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
                        &nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
                    </button>
                    <button type="button" id="registrar_tareas" style="font-weight: bold;font-size: 13px" class="btn btn-danger">
                        &nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Registrar
                    </button>
                    <button type="reset" id="limpiar" style="font-weight: bold;font-size: 13px; background: linear-gradient(#f4eb2f, #e5a32d); color: white " class="btn">
                        &nbsp;<span class="glyphicon glyphicon-retweet"></span>&nbsp;&nbsp;Limpiar
                    </button>
                </div>
                <br/>
        </form>
    </body>
</html>
{% endblock %}