gestion_actividades/actividades/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'actividades.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.urls')),
)

gestion_actividades/apps/asignaciones/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'asignar/', include('apps.asignaciones.asignar.urls')),
)

gestion_actividades/apps/registro/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'actividad/', include('apps.registro.actividad.urls')),
                       url(r'administrador/', include('apps.registro.administrador.urls')),
)

gestion_actividades/apps/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'^', include('apps.login.urls')),
                       url(r'^menu/', include('apps.menu.urls')),
                       )

gestion_actividades/apps/asignaciones/asignar/models.py
from django.db import models
from apps.registro.administrador.models import Actividad
from apps.configuraciones.models import Departamento
from django.contrib.auth.models import User

PORCENTAJE = (
    ('0', "Seleccione"),
    ('1', '10%'),
    ('2', '20%'),
    ('3', '30%'),
    ('4', '40%'),
    ('5', '50%'),
    ('6', '60%'),
    ('7', '70%'),
    ('8', '80%'),
    ('9', '90%'),
    ('10', '100%'),
)

class Asignar(models.Model):
    
    codigoA = models.CharField(max_length=50, null=True, blank=True)
    cod_actividad = models.ForeignKey(Actividad)
    codigoDepartamento = models.ForeignKey(Departamento, related_name='actividad_departamento', null=True, blank=True)
    codigoDepartamentoA = models.ForeignKey(Departamento, related_name='asignar_departamento', null=True, blank=True)
    nom_actividad  = models.TextField(max_length=300)
    des_actividad = models.TextField(max_length=300, null=True, blank=True)
    fecha_i    = models.DateField(auto_now_add=False, auto_now=False)
    fecha_p    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    fechaP_a    = models.DateField(auto_now_add=False, auto_now=False)
    indicaciones   = models.TextField(max_length=300, null=True, blank=True)
    porcentaje = models.CharField(choices=PORCENTAJE, default=0, max_length=3, null=True, blank=True)
    fecha_f    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    
    #  Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    
    class Meta:
        """ Ordena los registros en base a el campo fechaI_a."""
        ordering = ('codigoA',)  # Ordenado por

    def __unicode__(self):
        return self.codigoA

gestion_actividades/apps/registro/actividad/models.py
from django.db import models
from apps.registro.administrador.models import Actividad
from apps.configuraciones.models import Departamento
from django.contrib.auth.models import User

ESTATUS = (
    ('0', "Seleccione"),
    ('1', 'Activo'),
    ('2', 'Inactivo'),
)

PORCENTAJE = (
    ('0', "Seleccione"),
    ('1', '10%'),
    ('2', '20%'),
    ('3', '30%'),
    ('4', '40%'),
    ('5', '50%'),
    ('6', '60%'),
    ('7', '70%'),
    ('8', '80%'),
    ('9', '90%'),
    ('10', '100%'),
)

class Registros(models.Model):
    
    cod_actividad = models.ForeignKey(Actividad)
    cod_departamento = models.ForeignKey(Departamento, null=True, blank=True)
    nom_actividad = models.CharField(max_length=100)
    des_actividad = models.TextField(max_length=300)
    porcentaje = models.CharField(choices=PORCENTAJE, default=0, max_length=3)
    status     = models.CharField(choices=ESTATUS, default=0, max_length=1)
    fecha_i    = models.DateField(auto_now_add=False, auto_now=False)
    fecha_p    = models.DateField(auto_now_add=False, auto_now=False)
    fecha_f    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    observacion = models.TextField(null=True, blank=True)
    fecha_o    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
        
    #  Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    
    class Meta:
        """ Ordena los registros en base a el campo cod_estado."""
        ordering = ('cod_actividad',)  # Ordenado por

    def __unicode__(self):
        return self.cod_actividad

gestion_actividades/apps/registro/administrador/models.py
from django.db import models
from apps.configuraciones.models import Departamento
from django.contrib.auth.models import User

ESTATUS = (
    ('0', "Seleccione"),
    ('1', 'Activo'),
    ('2', 'Inactivo'),
)

PORCENTAJE = (
    ('0', "Seleccione"),
    ('1', '10%'),
    ('2', '20%'),
    ('3', '30%'),
    ('4', '40%'),
    ('5', '50%'),
    ('6', '60%'),
    ('7', '70%'),
    ('8', '80%'),
    ('9', '90%'),
    ('10', '100%'),
)

class Actividad(models.Model):
    cod_actividad = models.CharField(max_length=50,)
    nom_actividad = models.CharField(max_length=50,)
    des_actividad = models.TextField(max_length=300)
    departamento  = models.ForeignKey(Departamento, null=True, blank=True)
    status        = models.CharField(choices=ESTATUS, default=0, max_length=1)
    fecha_i       = models.DateField(auto_now_add=False, auto_now=False)
    fecha_p       = models.DateField(auto_now_add=False, auto_now=False)
    fecha_o       = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    observacion   = models.TextField(max_length=300, null=True, blank=True)
    porcentaje = models.CharField(choices=PORCENTAJE, default=0, max_length=3, null=True, blank=True)
    fecha_f       = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    
    #  Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    
    class Meta:
        """ Ordena los registros en base a el campo cod_actividad"""
        ordering = ('cod_actividad',)  # Ordenado por

    def __unicode__(self):
        return self.cod_actividad

gestion_actividades/apps/asignaciones/asignar/views.py
from django.views.generic import CreateView, ListView, UpdateView
from django.core.urlresolvers import reverse_lazy
from .models import Asignar
from django.contrib.auth.models import User
from apps.registro.administrador.models import Actividad
from apps.registro.actividad.models import Registros
from apps.configuraciones.models import Departamento
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db import connection
import time
from django.db.models import Q
import re

class RegistrarAsignar(CreateView):
    template_name = 'registros/asignaciones/asignacion.html'
    model = Asignar
    success_url = reverse_lazy("listandose") 
    
    def get_context_data(self, **kwargs):
        context = super(RegistrarAsignar, self).get_context_data(**kwargs)
        
        usuario = self.request.user
        departamento_id = usuario.usuariodepart.departamento_id

        actividades = Registros.objects.all()
        actividades_f = actividades.filter(cod_departamento_id=departamento_id) 
        actividades_v =  actividades_f.values('cod_actividad__id','cod_actividad__cod_actividad')
        codigoA = Asignar.objects.order_by('-id').values('codigoA')[:1] # ordenar de forma decendente y traer solo 
        if codigoA.count() > 0:
            codigoA = re.findall(r'\d+', codigoA[0]['codigoA']) # extraer solo numeros 
            codigoA =  int(codigoA[0]) # convertir a entero osea eliminar los 0 a las izquierda
            codigoA = "A"+str(codigoA+1).zfill(4) # sumo 1 y  rellenar con 4 "0" a la izquierda
        else:
            codigoA = "A"+str(codigoA.count()+1).zfill(4)
            
        usuario_id = self.request.user.id
        usuario = User.objects.get(id=usuario_id).username
        depar = Departamento.objects.all()
        departamento = Departamento.objects.all().exclude(id=departamento_id) ### Aqui excluye el usuario del departamento logueado de la lista para asignar actividades
        fecha_i = time.strftime("%d/%m/%Y")
        
        # dep = Asignar.objects.all().exclude(codigoDepartamentoA_id=usuario_id).values('codigoDepartamentoA')
        # departamento = dep.values('codigoDepartamentoA')
        # print 'aquiiii',departamento
        
        context['fecha_i'] = fecha_i
        context['codigoA'] = codigoA
        context['usuario'] = usuario
        context['lista_depar'] = depar
        context['lista_departamento'] = departamento
        context['actividades'] = actividades_v
        return context
    
    def post(self, request, *args, **kwargs):
        
        codigosasignar = request.POST.getlist('codigoDepartamentoA')
   
        asi = Asignar()

        for cod in codigosasignar:
            ids = Asignar.objects.order_by('-id').values('id')[:1]
            ids = ids[0]['id']+1
            print ids
            asi.codigoA = request.POST.get('codigoA')
            asi.codigoDepartamentoA_id = cod
            
            #########CONVERSION DE FECHAS#############
            fecha_i = request.POST.get('fecha_i')
            date = fecha_i.split("/")
            fecha_in = date[2]+"-"+date[1]+"-"+date[0]
            asi.fecha_i = fecha_in
            
            fecha_p = request.POST.get('fecha_p')
            date = fecha_p.split("/")
            fecha_pn = date[2]+"-"+date[1]+"-"+date[0]
            asi.fecha_p = fecha_pn
           
            fechaP_a = request.POST.get('fechaP_a')
            date = fechaP_a.split("/")
            fechaP_an = date[2]+"-"+date[1]+"-"+date[0] 
            asi.fechaP_a = fechaP_an
            ##########################################
            
            asi.cod_actividad_id=request.POST.get('cod_actividad')
            asi.codigoDepartamento_id=request.POST.get('codigoDepartamento')
            asi.nom_actividad=request.POST.get('nom_actividad')
            asi.des_actividad=request.POST.get('des_actividad')
            asi.indicaciones=request.POST.get('indicaciones')
            asi.porcentaje=request.POST.get('porcentaje')
            asi.user_create_id=request.POST.get('user_create')
            asi.id = ids
            asi.save()
            
        return HttpResponse('/menu/asignaciones/asignar/listandose/')
            
class ListarAsignar(ListView):
    template_name = 'registros/asignaciones/lista.html'
    model = Asignar
    
    def get_context_data(self, **kwargs):
        context = {}
        usuario_id = self.request.user.id
        es_administrador = self.request.user.groups.all().filter(name='administrador').exists()
        
        data = {}
        datos = []
            
        if es_administrador:
            actividades = Asignar.objects.all()
            actividades_f = actividades.filter(user_create_id=usuario_id)
            actividades_v = actividades.values('id','fecha_i', 'cod_actividad__cod_actividad','codigoDepartamento', 'codigoDepartamento__nom_departamento', 'codigoDepartamentoA__nom_departamento')
            for n in actividades_v:
                data = n
                datos.append(data)
        else:
            
            usuario = self.request.user.usuariodepart
            departamento_id = usuario.departamento_id
            
            actividades = Asignar.objects.all()
            actividades_f = actividades.filter(Q(codigoDepartamento=departamento_id) | Q(codigoDepartamentoA=departamento_id))
            actividades_v = actividades_f.values('id','fecha_i', 'cod_actividad__cod_actividad', 'codigoDepartamento', 'codigoDepartamento__nom_departamento', 'codigoDepartamentoA__nom_departamento')
            
            for n in actividades_v:
                data = n
                datos.append(data)
           
           

        context['listado'] = datos
        return context
    
class ActualizarAsignar(UpdateView):
    template_name = 'registros/asignaciones/ver.html'
    model = Asignar
    success_url = reverse_lazy("listandose")
    context_object_name = "asignar_act" 
    
    def get_context_data(self, **kwargs):
        context = super(ActualizarAsignar, self).get_context_data(**kwargs)

        usuario_id = self.request.user.id
        usuario = User.objects.get(id=usuario_id).username
        codigo = Actividad.objects.all()
        depar = Departamento.objects.all()
        departamento = Departamento.objects.all()
       
        context['usuario'] = usuario
        context['list_cod'] = codigo
        context['lista_depar'] = depar
        context['lista_departamento'] = departamento
        return context
    
    #### En esta seccion se actualiza el porcentaje
    #### para ser visualizado en actividades asignadas
    def post(self, request, *args, **kwargs):
    
        id_asi = request.POST.getlist('codigoA')
        coda = request.POST.get('codigoDepartamentoA')
        
        porcentaje = request.POST.get('porcentaje')
        usuarioU = request.POST.get('user_create')
        des_actividad = request.POST.get('des_actividad')
        print usuarioU
        
        fecha_f = request.POST.get('fecha_f')
        date = fecha_f.split("/")
        fecha_fn = date[2]+"-"+date[1]+"-"+date[0]
        
        fecha_p = request.POST.get('fecha_p')
        date = fecha_p.split("/")
        fecha_pn = date[2]+"-"+date[1]+"-"+date[0]
        
        Asignar.objects.filter(codigoA=id_asi,codigoDepartamentoA_id=coda).update(porcentaje=porcentaje, fecha_f=fecha_fn, fecha_p=fecha_pn, user_create_id=usuarioU, des_actividad=des_actividad)
        
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        add = form.save(commit=False)
        if form.is_valid():
            add.id = self.kwargs['pk']
            add.save()
        return HttpResponse('procesado')
    
def BuscarActivi(request):

    id_activi = request.GET['id']
    # id_registro = Registros.objects.filter(id=id_activi).values('cod_actividad_id')
    
    actividad = Actividad.objects.filter(id=id_activi)

    
    data = serializers.serialize('json', actividad,
                                 fields=('nom_actividad', 'des_actividad', 'fecha_i', 'fecha_p'))
   
    return HttpResponse(data, content_type='application/json')

def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

gestion_actividades/templates/registros/asignaciones/asignacion.html
{% extends "base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block contenido %}
<script type="text/javascript">
	$(document).ready(function(){
		
		$('#registrar_activi').click(function(e){
			
			//Para validar campos vacios
			var departamentoA = $('#codigoDepartamentoA').find('option').filter(':selected').val()
			var departamento = $('#codigoDepartamento').find('option').filter(':selected').val()
			var codigo = $('#id_cod_actividad').find('option').filter(':selected').val()
	
			if (departamento == 0) {
				bootbox.alert('Debe seleccionar el departamento dependiente de la actividad', function() {
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#codigoDepartamento').parent('div').addClass('has-error'); // colocar class has-error de boostrap
					$('#codigoDepartamento').focus() 
				});
			}else if (codigo == 0){
				bootbox.alert('Debe seleccionar el codigo, según el departamento seleccionado', function() {
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#id_cod_actividad').parent('div').addClass('has-error'); // colocar class has-error de boostrap
					$('#id_cod_actividad').focus() 
				});
			}else if (departamentoA == 0){
				bootbox.alert('Debe seleccionar el departamento para asignar la actividad', function(){
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#codigoDepartamentoA').parent('div').addClass('has-error');
					$('#codigoDepartamentoA').focus() 
				});
			}
			else if ($('#indicaciones').val().trim() == ''){
				bootbox.alert('Debe indicar los requerimientos para esta actividad', function(){
					$('.nav-tabs a[href=#tabs_A]').tab('show') ;
					$('#indicaciones').parent('div').addClass('has-error');
					$('#indicaciones').focus() 
				});
			}
			else{
				$('#codigoA,#nom_actividad,#id_fecha_i,#id_fecha_p,#id_des_actividad').prop('disabled',false);
				$.post('',$('#form_asignar').serialize(),function(response){
					if (response == 'existe_cod') {
						bootbox.alert("Esta actividad ya esta registrada", function() {
							$('.nav-tabs a[href=#tabs_A]').tab('show') ;
							$('#codigoA').parent('div').addClass('has-error'); // colocar class has-error de boostrap
						});
					}else{
						url = '/menu/asignaciones/asignar/listandose/'
						window.location = url
					}
				});
			}
	
		})
		
		$('#fechaP_a').datepicker({
			format: "dd/mm/yyyy",
			language: "es",
			startDate: "+1d",
			//daysOfWeekDisabled: "0,6",
			autoclose: true,
			
		})
		
		//.change(function () {
		//	var primera = Date.parse($("#id_fecha_p").val()); //fecha pautada
		//	var segunda = Date.parse($("#fechaP_a").val()); //fecha asignar
		//			 
		//		if (segunda > primera) {
		//			alert("Debe seleccionar una fecha menor");
		//			$("#fechaP_a").val($("#id_fecha_p").val())
		//		}
		//});
		
		//.on('changeDate', function(ev){
		//	var primera = Date.parse($("#id_fecha_p").val()); //fecha pautada
		//	var segunda = Date.parse($("#fechaP_a").val()); //fecha asignar
		//	//var value = $("#id_fecha_p input").datepicker("getDate");
		//	//
		//	//$("#fechaP_a").datepicker("setValue", "02-17-2012");
		//
		//		if (segunda > primera) {
		//			alert("Debe seleccionar una fecha menor");
		//			$("#fechaP_a").val('')
		//		}
		//});
		 
		///// Para validar campos numericos, alfanumericos y seleccion
		$("#id_cod_actividad,#codigoDepartamentoA").select2();
		$('#nombreActividad,#indicaciones').alphanumeric({allow:"´,@,-.# "}); //Valida solo valores numericos y texto
		//$('#id_edad,#id_cedula,#id_telefono1,#id_telefono2').numeric(); //Valida solo permite valores numericos
			
		$('#volver').click(function(){
			url = '/menu/asignaciones/asignar/listandose'
			window.location = url
		})
		$('#limpiar').click(function(){
			$('#codigoDepartamento,#id_cod_actividad,#codigoDepartamentoA').select2('val', '0');
		})
		
		$("#todas_opciones").click(function() {  
			if($(this).is(':checked')) {
				var data = $('#codigoDepartamentoA').find('option')
				var valores = new Array();
				
				$.each(data, function() {
					
					valores.push($(this).val())
				});
				//console.log(valores)
				$('#codigoDepartamentoA').val(valores).trigger("change"); 
			}  
		});
			
	});

</script>
<style>
    label{
        font-weight: bold
    }
</style>
    <html>
        <body>
            <form method="post" id="form_asignar" enctype="multipart/form-data">
                {% csrf_token %}
				<br/>
                <div style="width: 100%;text-transform:uppercase;box-shadow: 0 1px 5px rgba(0,0,0,.85); text-align: left" class="panel panel-danger">
					<div class="panel-heading">
						<label style="float: left" class="panel-title " ><a style="color: white" href="/menu/asignaciones/asignar/listandose" >Actividad</a>
						> Asignar</label>
						<br>
					</div>
                    <div class="panel-body">
                        <!-- Apertura de Tabs (Secciones) -->
                        <ul class="nav nav-tabs">
                            <li class="active" data-toggle="popover" data-trigger="focus" title="Datos de la actividad" data-content="En este panel se ingresan los datos requeridos para asignar una actividad" data-placement="top">
                                <a data-toggle="tab" href="#tabs_A">Tareas</a>
                            </li>
                        </ul>
                        <!-- Cierre de Tabs (Secciones) -->
                        <!-- Apertura de tabs (Contenidos) -->
                        <div class="tab-content">
                            <div id="tabs_A" class="tab-pane fade in active">
                                <div class="panel-body">
                                <!-- Apertura de datos para asignar actividad a otros departamentos  -->
								<div class="form-group col-xs-1"><label>Usuario</label></div>
                                <div class="form-group col-xs-2">
                                    <span style="color: red; font-weight: bold">{{usuario|upper}}</span>
                                </div>
								<div class="form-group col-xs-5">
									<input id="codigoAB" maxlength="30"  style="width: 100%;" name="codigoAB" type="hidden" value="" disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Código</label></div>
								<div class="form-group col-xs-3">
									<input id="codigoA" maxlength="30"  style="width: 100%;" name="codigoA" type="text" value="{{codigoA}}" disabled='disabled'/>
								</div>
								<br/><br/><br/>
                                <fieldset><legend style="text-align: left">Asignar Tareas a otros Departamentos</legend></fieldset>
                                <div class="form-group col-xs-1"><label>Gerencia</label></div>
                                <div class="form-group col-xs-11">
                                    <input id="cod_departamento" name="codigoDepartamento" type="hidden" value="{{user.usuariodepart.departamento.id}}"/>
									<input id="departamento" maxlength="30"  style="width: 100%;text-align: left" name="departamento" type="text" disabled='disabled' value="{{user.usuariodepart.departamento.nom_departamento}}"/>
                                </div>
								<div class="form-group col-xs-1"><label>Código</label></div>
								<div class="form-group col-xs-2">
									<select style="width:100%;text-align: center" class="form-control input-sm" id="id_cod_actividad" name="cod_actividad" >
										<option value="0">SELECCIONE</option>
										{% for act in actividades %}
											<option value="{{act.cod_actividad__id}}">{{act.cod_actividad__cod_actividad}}</option>
										{% endfor %}
									</select>
								</div>
								<div class="form-group col-xs-1"><label>Nombre</label></div>
								<div class="form-group col-xs-8">
									<input id="nom_actividad" maxlength="30"  style="width: 100%; text-align: center; text-transform:uppercase;" name="nom_actividad" type="text" placeholder="Nombre de la actividad" disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Descripción</label></div>
								<div class="form-group col-xs-12">
									<textarea cols="70" id="id_des_actividad" name="des_actividad" rows="05" style="width: 100%;text-align: justify; text-transform:uppercase;" placeholder="Descripción de la actividad" disabled='disabled'></textarea>
								</div>
								<div class="form-group col-xs-1"><label>Inicial</label></div>
								<div class="form-group col-xs-3">
									<input id="id_fecha_i" maxlength="30"  style="width: 100%;text-align: center" name="fecha_i" type="text" disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Pautada</label></div>
								<div class="form-group col-xs-3">
									<input id="id_fecha_p" maxlength="30"  style="width: 100%;text-align: center" name="fecha_p" type="text" disabled='disabled'/>
								</div>
								<div class="form-group col-xs-1"><label>Asignada</label></div>
								<div class="form-group col-xs-3">
									<input id="fechaP_a" maxlength="30"  style="width: 100%;text-align: center" name="fechaP_a" type="text" />
								</div>
								<div class="form-group col-xs-2"><label>Seleccionar Todas</label></div>
								<div class="form-group col-xs-10">
									<input type="checkbox" id="todas_opciones">
								</div>
								<div class="form-group col-xs-12">
									<label>Asignar</label>
									<select style="width:100%;text-align: left" class="form-control input-sm" id="codigoDepartamentoA" name="codigoDepartamentoA" data-placeholder="SELECCIONE" multiple='multiple'>
										{% for dep in lista_departamento %}
											<option value="{{dep.id}}">{{dep.nom_departamento}}</option>
										{% endfor %}
									</select>
								</div>
								<div class="form-group col-xs-12">
									<label>Indicaciones</label>
									<textarea cols="70" id="indicaciones" name="indicaciones" rows="05" style="width: 100%;text-align: justify; text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" placeholder="Indique su requerimiento"></textarea>
								</div>
                            </div>
                       </div>
                    </div>
                </div>
                
                <input id='user_create' type="hidden" name='user_create' value='{{ user.id }}'>
				<input id='porcentaje' type="hidden" name='porcentaje' value='0'>
                <div class="row" style="text-align: center">
                    <button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
                        &nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
                    </button>
                    <button type="button" id="registrar_activi" style="font-weight: bold;font-size: 13px" class="btn btn-danger">
                        &nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Registrar
                    </button>
                    <button type="reset" id="limpiar" style="font-weight: bold;font-size: 13px; background: linear-gradient(#f4eb2f, #e5a32d); color: white " class="btn">
                        &nbsp;<span class="glyphicon glyphicon-retweet"></span>&nbsp;&nbsp;Limpiar
                    </button>
                </div>
                <br/>
        </form>
    </body>
</html>
{% endblock %}