gestion_actividades/actividades/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'actividades.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.urls')),
)

gestion_actividades/apps/registro/actividad/urls.py
from django.conf.urls import patterns, include, url
from .views import RegistrarActividad, ListarActividad, ActualizarActividad, EliminarActividad, Activo, BuscarActividad
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'registro/$', RegistrarActividad.as_view(),name='registrar'),
    url(r'listado/$', ListarActividad.as_view(),name='lista'),
    url(r'edita/(?P<pk>\d+)$', ActualizarActividad.as_view(),name='actualiza'),
    url(r'elimina/(?P<pk>\d+)$', EliminarActividad.as_view(),name='elimina'),
    url(r'^activo/$', login_required(Activo.as_view(),
                                                login_url='/'), name='estatus_activo'),
    url(r'^busqueda_solicitud/$', 'apps.registro.actividad.views.BuscarActividad', name='busqueda_solicitud'),
)

gestion_actividades/apps/registro/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'actividad/', include('apps.registro.actividad.urls')),
                       url(r'administrador/', include('apps.registro.administrador.urls')),
)

gestion_actividades/apps/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'^', include('apps.login.urls')),
                       url(r'^menu/', include('apps.menu.urls')),
                       )

gestion_actividades/apps/registro/actividad/models.py
from django.db import models
from apps.registro.administrador.models import Actividad
from apps.configuraciones.models import Departamento
from django.contrib.auth.models import User

ESTATUS = (
    ('0', "Seleccione"),
    ('1', 'Activo'),
    ('2', 'Inactivo'),
)

PORCENTAJE = (
    ('0', "Seleccione"),
    ('1', '10%'),
    ('2', '20%'),
    ('3', '30%'),
    ('4', '40%'),
    ('5', '50%'),
    ('6', '60%'),
    ('7', '70%'),
    ('8', '80%'),
    ('9', '90%'),
    ('10', '100%'),
)

class Registros(models.Model):
    
    cod_actividad = models.ForeignKey(Actividad)
    cod_departamento = models.ForeignKey(Departamento, null=True, blank=True)
    nom_actividad = models.CharField(max_length=100)
    des_actividad = models.TextField(max_length=300)
    porcentaje = models.CharField(choices=PORCENTAJE, default=0, max_length=3)
    status     = models.CharField(choices=ESTATUS, default=0, max_length=1)
    fecha_i    = models.DateField(auto_now_add=False, auto_now=False)
    fecha_p    = models.DateField(auto_now_add=False, auto_now=False)
    fecha_f    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    observacion = models.TextField(null=True, blank=True)
    fecha_o    = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
        
    #  Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    
    class Meta:
        """ Ordena los registros en base a el campo cod_estado."""
        ordering = ('cod_actividad',)  # Ordenado por

    def __unicode__(self):
        return self.cod_actividad

gestion_actividades/apps/registro/administrador/models.py
from django.db import models
from apps.configuraciones.models import Departamento
from django.contrib.auth.models import User

ESTATUS = (
    ('0', "Seleccione"),
    ('1', 'Activo'),
    ('2', 'Inactivo'),
)

PORCENTAJE = (
    ('0', "Seleccione"),
    ('1', '10%'),
    ('2', '20%'),
    ('3', '30%'),
    ('4', '40%'),
    ('5', '50%'),
    ('6', '60%'),
    ('7', '70%'),
    ('8', '80%'),
    ('9', '90%'),
    ('10', '100%'),
)

class Actividad(models.Model):
    cod_actividad = models.CharField(max_length=50,)
    nom_actividad = models.CharField(max_length=50,)
    des_actividad = models.TextField(max_length=300)
    departamento  = models.ForeignKey(Departamento, null=True, blank=True)
    status        = models.CharField(choices=ESTATUS, default=0, max_length=1)
    fecha_i       = models.DateField(auto_now_add=False, auto_now=False)
    fecha_p       = models.DateField(auto_now_add=False, auto_now=False)
    fecha_o       = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    observacion   = models.TextField(max_length=300, null=True, blank=True)
    porcentaje = models.CharField(choices=PORCENTAJE, default=0, max_length=3, null=True, blank=True)
    fecha_f       = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    
    #  Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    
    class Meta:
        """ Ordena los registros en base a el campo cod_actividad"""
        ordering = ('cod_actividad',)  # Ordenado por

    def __unicode__(self):
        return self.cod_actividad

gestion_actividades/apps/registro/actividad/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Registros
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from apps.registro.administrador.models import Actividad
from apps.configuraciones.models import Departamento
from apps.asignaciones.asignar.models import Asignar
from django.core import serializers
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db import connection
import time
import json
from apps.registro.administrador.models import Actividad
from django.db.models import Q

class RegistrarActividad(CreateView):
    template_name = 'registros/actividad/actividad.html'
    model = Registros
    success_url = reverse_lazy("lista") 
    
    def get_context_data(self, **kwargs):
        context = super(RegistrarActividad, self).get_context_data(**kwargs)
        
        usuario = self.request.user
        departamento_id = usuario.usuariodepart.departamento_id
        
        id_reg = Registros.objects.all().values('cod_actividad_id') ### se hace una busqueda del campo para la comparacion
        
        actividades = Actividad.objects.all()
       
        actividades_f = actividades.filter(departamento_id=departamento_id).exclude(id__in=id_reg) ### aqui se excluyen las actividades que ya estan agregadas en la lista de registros
        actividades_v =  actividades_f.values('id','cod_actividad')

        fecha_i = time.strftime("%d/%m/%Y")
        fecha_f = time.strftime("%d/%m/%Y")
        usuario_id = self.request.user.id
        usuario = User.objects.get(id=usuario_id).username
        actividad = Actividad.objects.all()
        departamento = Departamento.objects.all()
      
        context['fecha_i'] = fecha_i
        context['fecha_f'] = fecha_f
        context['usuario'] = usuario
        context['lista_actividades'] = actividad
        context['lista_departamento'] = departamento
        context['actividades'] = actividades_v
        return context
       
    def post(self, request, *args, **kwargs):
     
        codigo = request.POST.get('cod_actividad')
        
        existe_codigo = Registros.objects.filter(cod_actividad=codigo).exists()
        if existe_codigo:
            return HttpResponse('existe_cod')
        else:
            
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            
            if form.is_valid():
                
                add = form.save(commit=False)
                add.save()
                
                ##### Desde aqui hasta la var "a", se actualiza
                ##### el campo "porcentaje" del modelo Actividad
                ##### una vez que se agregue la actividad en el departamento correspondiente
                
                porcentaje = request.POST.get('porcentaje')
                porcentaje = request.POST.get('porcentaje')
                
                id_adm = Actividad.objects.filter(id=codigo).values('id')
                
                a = Actividad.objects.filter(id=id_adm).update(porcentaje=porcentaje)
                
                return HttpResponse('/menu/registros/actividad/listado/')
    
class ListarActividad(ListView):
    template_name = 'registros/actividad/listado.html'
    model = Registros
    
    def get_context_data(self, **kwargs):
        context = {}
       
        usuario_id = self.request.user.id
        
        # Captura del ID del Grupo 'administrador'
        cursor = connection.cursor()
        sql_gru = "SELECT id FROM auth_group WHERE name = 'administrador'"
        cursor.execute(sql_gru)
        row = dictfetchall(cursor)
        # print row
        if row == []:
            id_grupo = 0
        else:
            id_grupo = row[0]['id']
        
        # Consulta a la tabla user_group si el usuario pertenece al grupo 'Web'
        cursor = connection.cursor()
        sql_use = "SELECT id FROM auth_user_groups"
        sql_use += " WHERE user_id=%s and group_id =%s;"
        cursor.execute(sql_use, [usuario_id, id_grupo])
        row2 = dictfetchall(cursor)
    
        if row2 == []:
            encuestas = Registros.objects.all()
            encuestas = Registros.objects.filter(user_create_id=usuario_id)
            encuestas = encuestas.order_by('id').reverse()
        else:            
            encuestas = Registros.objects.all()
        
        context['listado'] = encuestas
        return context

class Activo(UpdateView):
    
    def post(self, request, *args, **kwargs):
        response_data = {}
        id_act = self.request.POST.get('id')
        Registros.objects.filter(id=id_act).update(status='1')
        
        ##### en esta seccion se actualiza el status al hacer el cambio en menu gerente(agregar actividad)
        id_reg = Registros.objects.filter(id=id_act).values('cod_actividad_id')
        Actividad.objects.filter(id=id_reg).update(status='1')
                
        return HttpResponse('exito')

class ActualizarActividad(UpdateView):
    template_name = 'registros/actividad/actualiza.html'
    model = Registros
    success_url = reverse_lazy("lista")
    context_object_name = "registro_act" 
    
    def get_context_data(self, **kwargs):
        context = super(ActualizarActividad, self).get_context_data(**kwargs)
    
        usuario_id = self.request.user.id
        usuario = User.objects.get(id=usuario_id).username
        actividad = Actividad.objects.all()
        departamento = Departamento.objects.all()
        
        context['usuario'] = usuario
        context['lista_actividades'] = actividad
        context['lista_departamento'] = departamento
        return context
    
    #### En esta seccion se actualiza el porcentaje y la fecha final
    #### para ser visualizado en el menu administrador y hacer la compararcion para el estado de eficiencia
    def post(self, request, *args, **kwargs):
    
        id_act = request.POST.get('cod_actividad')
        porcentaje = request.POST.get('porcentaje')
        fecha_f = request.POST.get('fecha_f')
        
        id_por = Registros.objects.filter(cod_actividad=id_act).values('cod_actividad_id')
        date = fecha_f.split("/")
        try:
            nueva_fecha = date[2]+"-"+date[1]+"-"+date[0]
        
        except:
            nueva_fecha = None
            
        if nueva_fecha != None:
        
            Actividad.objects.filter(id=id_por).update(porcentaje=porcentaje, fecha_f=nueva_fecha)
            Registros.objects.filter(cod_actividad_id=id_por).update(porcentaje=porcentaje, fecha_f=nueva_fecha)
    
        return HttpResponse('procesado')

class EliminarActividad(DeleteView):
    template_name = 'registros/actividad/elimina.html'
    model = Registros
    
    def delete(self, request, *args, **kwargs):
        response_data = {}
        
        id_registro = Registros.objects.filter(id=self.kwargs['pk']).values('cod_actividad_id')
        
        existe  = Asignar.objects.filter(cod_actividad_id=id_registro)

        if existe.exists():
            response_data['existe'] = 'si'
        else:
            
            existe = Registros.objects.filter(id=self.kwargs['pk'])
            if existe.exists():
                self.object = self.get_object()
                self.object.delete()
                response_data['eliminado'] = 'ok'
        
        return HttpResponse(json.dumps(response_data), status=200, content_type='application/json')

def BuscarActividad(request):

    id_act = request.GET['id']
    actividades = Actividad.objects.filter(id=id_act)
    
    data = serializers.serialize('json', actividades,
                                 fields=('nom_actividad', 'fecha_i', 'fecha_p', 'des_actividad'))
    
    return HttpResponse(data, content_type='application/json')

def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

gestion_actividades/templates/registros/administrador/actividades.html
{% extends "base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block contenido %}

<html>

<script type="text/javascript">
$(document).ready(function(){
    
    $('#registro_act').click(function(e){
		var departamento = $('#departamento').find('option').filter(':selected').val()
        
        //Para validar campos vacios

		if ($('#nom_actividad').val().trim() == '') {
            bootbox.alert('El nombre de la actividad no debe estar en blanco', function() {
				$('.nav-tabs a[href=#tabs_A]').tab('show') ;
				$('#nom_actividad').parent('div').addClass('has-error'); // colocar class has-error de boostrap
				$('#nom_actividad').focus() 
			});
		}else if (departamento == 0){
			bootbox.alert('Debe seleccionar el departamento', function() {
				$('.nav-tabs a[href=#tabs_A]').tab('show') ;
				$('#departamento').parent('div').addClass('has-error'); // colocar class has-error de boostrap
				$('#departamento').focus() 
			});
		}else if ($('#des_actividad').val().trim() == ''){
			bootbox.alert('La descripción de la actividad no debe estar en blanco', function() {
				$('.nav-tabs a[href=#tabs_A]').tab('show') ;
				$('#des_actividad').parent('div').addClass('has-error'); // colocar class has-error de boostrap
				$('#des_actividad').focus() 
			});
		}		
		else{
			$('#fecha_i,#fecha_o,#cod_actividad,#observacion').prop('disabled',false);
			$.post('',$('#form_actividad').serialize(),function(response){
				if (response == 'existe_codigo') {
					bootbox.alert("Esta actividad ya esta registrada", function() {
						$('.nav-tabs a[href=#tabs_A]').tab('show') ;
						$('#cod_actividad').parent('div').addClass('has-error'); // colocar class has-error de boostrap
					});
				}else{
					url = '/menu/registros/administrador/listar/'
					window.location = url
				}
			});
		}

    })
	$('#fecha_i,#fecha_p,#fecha_o').datepicker({
		format: "dd/mm/yyyy",
		language: "es",
		startDate: "+1d",
		//daysOfWeekDisabled: "0,6",
		autoclose: true,
	})
	
	///// Para validar campos numericos, alfanumericos y seleccion
	$("#departamento").select2();
    $('#nom_actividad,#des_actividad,#observacion').alphanumeric({allow:"´,@,-.# "}); //Valida solo valores numericos y texto
    //$('#id_edad,#id_cedula,#id_telefono1,#id_telefono2').numeric(); //Valida solo permite valores numericos
	
    $('#volver').click(function(){
        url = '/menu/registros/administrador/listar/'
        window.location = url
    })
    $('#limpiar').click(function(){
        $('#departamento').select2('val', '0');
    })
})

</script>
<style>
    label{
        font-weight: bold
    }
</style>
<body>
{% load templatag_grupos %}
{% ifusergroup administrador %}	
    <form method="post" id="form_actividad" enctype="multipart/form-data">
	{% csrf_token %}
	<br/>
	<div style="width: 100%;text-transform:uppercase;box-shadow: 0 1px 5px rgba(0,0,0,.85); text-align: left" class="panel panel-danger">
	    <div class="panel-heading">
			<label style="float: left" class="panel-title " ><a style="color: white" href="/menu/registros/administrador/listar/" >Actividad</a>
			> Registrar</label>
			<br>
		</div>
			<div class="panel-body">
				<!-- Apertura de Tabs (Secciones) -->
				<ul class="nav nav-tabs">
					<li class="active" data-toggle="popover" data-trigger="focus" title="Datos del equipo" data-content="En este panel se ingresan los datos requeridos para registrar una actividad" data-placement="top">
						<a data-toggle="tab" href="#tabs_A">Datos Requeridos</a>
					</li>
				</ul>
				<!-- Cierre de Tabs (Secciones) -->
				<!-- Apertura de tabs (Contenidos) -->
				<div class="tab-content">
					<div id="tabs_A" class="tab-pane fade in active">
						 <div class="panel-body">
							<!-- Apertura de datos principales de la empresa  -->							
							<div class="form-group col-xs-1"><label>Usuario</label></div>
                            <div class="form-group col-xs-3">
                                <span style="color: red; font-weight: bold;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();">{{usuario|upper}}</span>
                            </div>
							<div class="form-group col-xs-1"><label>Estatus</label></div>
							<div class="form-group col-xs-3">
                                <span style="color: red; font-weight: bold;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();">INACTIVO</span>
                            </div>
							<div class="form-group col-xs-1"><label>Código</label></div>
							<div class="form-group col-xs-3">
								<input id="cod_actividad" maxlength="30"  style="width: 100%;text-align: center;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" name="cod_actividad" type="text" value="{{codigo}}" disabled="disabled"/>
							</div>
							<br/><br/><br/>
                            <div class="form-group col-xs-1"><label>Inicial</label></div>
                            <div class="form-group col-xs-3">
                                <input id="fecha_i" maxlength="30"  style="width: 100%;text-align: center;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" name="fecha_i" type="text" value="{{fecha_i}}" disabled="disabled"/>
                            </div>   
							<div class="form-group col-xs-1"><label>Pautada</label></div>
                            <div class="form-group col-xs-3">
                                <input id="fecha_p" maxlength="30"  style="width: 100%;text-align: center;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" name="fecha_p" type="text" />
                            </div>
							<!--<div class="form-group col-xs-1"><label>Incidencia</label></div>
                            <div class="form-group col-xs-3">
                                <input id="fecha_o" maxlength="30" placeholder="opcional" style="width: 100%;text-align: center;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" name="fecha_o" type="text" disabled='disabled'/>
                            </div>-->
							<br/><br/><br/><br/>
							
							<fieldset><legend style="text-align: left">Descripción de la actividad</legend></fieldset>
							<div class="form-inline">
								<div class="form-inline">
                                <div class="form-group col-xs-2"><label>Departamento</label></div>
								<div class="form-group col-xs-10">
									<select style="width:100%;text-align: left;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" class="form-control input-sm" id="departamento" name="departamento" >
										<option value="0">SELECCIONE</option>
										{% for dep in lista_departamento %}
                                        
											<option value="{{dep.id}}">{{dep.nom_departamento}}</option>
                                        
                                        {% endfor %}
									</select>
								</div>
								</div>
								<br/><br/><br/>
								<div class="form-group col-xs-2"><label>Actividad</label></div>
								<div class="form-group col-xs-10">
									<input id="nom_actividad" maxlength="30"  style="width: 100%;text-align: left;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" name="nom_actividad" placeholder="Nombre de la actividad" type="text" />
								</div>
							</div>
							<br/><br/><br/>
							<div class="form-group col-xs-12">
                                <textarea cols="70" id="des_actividad" name="des_actividad" rows="05" style="width: 100%;text-align: justify;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" placeholder="Descripción de la actividad"></textarea>
                            </div>
							<br/><br/><br/>
							<br/><br/>
							<div class="form-group col-xs-12">
                                <textarea style="visibility: hidden" cols="70" id="observacion" name="observacion" rows="05" style="width: 100%;text-align: justify;text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" placeholder="Descripción de la observación"></textarea>
                            </div>
							<input id='id_porcentaje' type="hidden" name='porcentaje' value='0'>
						 </div>
					</div>
				</div>
				<!-- Cierre de tabs (Contenidos) -->   
			</div>

		<input id='status' type="hidden" name='status' value='2'> 
	    <input id='user_create' type="hidden" name='user_create' value='{{ user.id }}'>
	    <div class="row" style="text-align: center">
			<button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
				&nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
			</button>
			<button type="button" id="registro_act" style="font-weight: bold;font-size: 13px" class="btn btn-danger">
				&nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Registrar
			</button>
			<button type="reset" id="limpiar" style="font-weight: bold;font-size: 13px;background: linear-gradient(#f4eb2f, #e5a32d); color: white " class="btn">
				&nbsp;<span class="glyphicon glyphicon-retweet"></span>&nbsp;&nbsp;Limpiar
			</button>
	    </div>
		<br/>
	</div>
	<br/>

    </form>
{% else %}
<img src="{{ STATIC_URL }}img/disculpe.png" style="width: auto"/>
{% endifusergroup %}
</body>
</html>

{% endblock %}

gestion_actividades/templates/registros/administrador/eliminar.html
{% extends "base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block contenido %}
<script type="text/javascript">
$(document).ready(function(){
	 $('#volver').click(function(){
        url = '/menu/registros/administrador/listar/'
        window.location = url
    })
})
</script>
	<form method="post" id="formactividad" class="form-horizontal">
		{% csrf_token %}
		<table>
			<br/>
			<div class="panel panel-default" style='width:70%'>
				<div class="panel-heading" style="width:100%;color:#1A1A1A;font-size: 20px;">
				</div>
				<div class="panel-body">
					<div class="form-inline">
						<div class="form-group col-xs-6">
							<label id="nombre">Eliminar:{{listado.nom_actividad}}</label>
						</div>
					</div>
				</div>
			</div>
		</table>
		<div class="row" style="text-align: left">
		   <button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
			   &nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
		   </button>
		   <button type="submit" id="eliminar" style="font-weight: bold;font-size: 13px" class="btn btn-info"/>
			   &nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Eliminar
		   </button>
	   </div>
	</form>

{% endblock contenido%}